=== mdfass/spec-toolkit-java/src/main/resources/shared-services-internal/specification.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           targetNamespace="https://magento.com/open-specification"
           xmlns="https://magento.com/open-specification"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="specification" type="SpecificationType"/>

  <xs:group name="DescriptionGroup">
    <xs:sequence>
      <xs:element type="xs:string" name="summary" minOccurs="1" maxOccurs="1"/>
      <xs:element type="xs:string" name="description" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:group>

  <xs:complexType name="SpecificationType">
    <xs:sequence>
      <xs:choice maxOccurs="unbounded" minOccurs="0">
        <xs:element type="ImportType" name="import"/>
        <xs:element type="ModuleType" name="module"/>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ModuleType">
    <xs:sequence>
      <xs:choice maxOccurs="unbounded" minOccurs="0">
        <xs:element type="ServiceType" name="service"/>
        <xs:element type="StructType" name="struct"/>
        <xs:element type="EnumType" name="enum"/>
        <xs:element type="ExtensionType" name="extension"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute type="ModuleNameType" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="ImportType">
    <xs:attribute type="xs:token" name="location" use="required"/>
  </xs:complexType>

  <xs:complexType name="ServiceType">
    <xs:sequence>
      <xs:group ref="DescriptionGroup"/>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element type="QueryType" name="query"/>
        <xs:element type="EventType" name="event"/>
        <xs:element type="CommandType" name="command"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute type="ServiceNameType" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="InteractionType" abstract="true">
    <xs:sequence>
      <xs:group ref="DescriptionGroup"/>
      <xs:element type="xs:boolean" name="extensible" minOccurs="1"/>
      <xs:element name="status" type="StatusType" minOccurs="1" maxOccurs="1" />
      <xs:element name="arguments" minOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="PropertyType" name="argument" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="InteractionNameType" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="CommandType">
    <xs:complexContent>
      <xs:extension base="InteractionType">
        <xs:sequence>
          <xs:element type="xs:token" name="returns" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="QueryType">
    <xs:complexContent>
      <xs:extension base="InteractionType">
        <xs:sequence>
          <xs:element type="xs:token" name="returns" minOccurs="1" maxOccurs="1"/>
          <xs:element type="SearchableFieldsType" name="searchable_fields" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="SearchableFieldsType">
    <xs:sequence>
      <xs:element name="field" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:group ref="DescriptionGroup"/>
            <xs:element type="SearchableFieldTypeNameType" name="type" minOccurs="0"/>
          </xs:sequence>
          <xs:attribute name="name" type="SearchableFieldNameType" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="EventType">
    <xs:complexContent>
      <xs:extension base="InteractionType"/>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="StructType" mixed="true">
    <xs:sequence>
      <xs:group ref="DescriptionGroup"/>
      <xs:element type="xs:boolean" name="extensible" minOccurs="1"/>
      <xs:element name="properties" minOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="PropertyType" name="property" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="xs:token" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="ExtensionType" mixed="true">
    <xs:sequence>
      <xs:group ref="DescriptionGroup"/>
      <xs:element name="properties" minOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="PropertyType" name="property" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="xs:token" name="extends" use="required"/>
    <xs:attribute type="xs:token" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="PropertyType">
    <xs:sequence>
      <xs:group ref="DescriptionGroup"/>
      <xs:element type="PropertyTypeNameType" name="type" minOccurs="1"/>
      <xs:element type="xs:boolean" name="required" minOccurs="1"/>
    </xs:sequence>
    <xs:attribute type="xs:token" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="EnumType">
    <xs:sequence>
      <xs:element type="xs:token" name="value" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:token" name="name" use="required"/>
  </xs:complexType>

  <xs:simpleType name="StatusType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="public"/>
      <xs:enumeration value="draft"/>
      <xs:enumeration value="beta"/>
      <xs:enumeration value="deprecated"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="PropertyTypeNameType">
    <xs:restriction base="xs:token" />
  </xs:simpleType>

  <xs:simpleType name="ModuleNameType">
    <xs:restriction base="xs:token">
      <xs:pattern value="[a-z][a-z0-9_]*\.[a-z][a-z0-9_]*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ServiceNameType">
    <xs:restriction base="xs:token">
      <xs:pattern value="[a-z][a-z0-9_]*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="SearchableFieldTypeNameType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="string"/>
      <xs:enumeration value="integer"/>
      <xs:enumeration value="float"/>
      <xs:enumeration value="boolean"/>
      <xs:enumeration value="datetime"/>
      <xs:enumeration value="blob"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="InteractionNameType">
    <xs:restriction base="xs:token">
      <xs:pattern value="[a-z][a-z0-9_]*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="SearchableFieldNameType">
    <xs:restriction base="xs:token">
      <xs:pattern value="[a-zA-Z_]*" />
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== mdfass/spec-toolkit-java/src/main/resources/shared-services-internal/postsales/product_return_repository.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="https://magento.com/open-specification"
               xsi:schemaLocation="https://magento.com/open-specification ../specification.xsd">

    <module name="magento.postsales">

        <service name="product_return_repository">
            <summary>Product return Repository</summary>
            <query name="search">
                <summary>Search product returns by criteria</summary>
                <extensible>false</extensible>
                <status>deprecated</status>
                <arguments>
                    <argument name="query">
                        <summary>Query</summary>
                        <type>magento.common.query</type>
                        <required>false</required>
                    </argument>
                </arguments>
                <returns>magento.postsales.return_update_collection</returns>
            </query>
        </service>


    </module>

</specification>

=== mdfass/spec-toolkit-java/src/main/resources/shared-services-internal/postsales/return_repository.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="https://magento.com/open-specification"
               xsi:schemaLocation="https://magento.com/open-specification ../specification.xsd">

    <module name="magento.postsales">

        <service name="return_repository">
            <summary>Return Repository</summary>
            <query name="search">
                <summary>Search returns by criteria</summary>
                <extensible>false</extensible>
                <status>public</status>
                <arguments>
                    <argument name="query">
                        <summary>Query</summary>
                        <type>magento.common.query</type>
                        <required>false</required>
                    </argument>
                </arguments>
                <returns>magento.postsales.return_update_collection</returns>
                <searchable_fields>
                    <field name="source_id">
                        <summary>Source ID</summary>
                    </field>
                    <field name="sales_channel">
                        <summary>Sales channel</summary>
                    </field>
                    <field name="rma">
                        <summary>RMA</summary>
                    </field>
                    <field name="sku">
                        <summary>SKU</summary>
                    </field>
                    <field name="status">
                        <summary>Status</summary>
                    </field>
                    <field name="order_id">
                        <summary>Order ID</summary>
                    </field>
                    <field name="status_date">
                        <summary>Status Date</summary>
                    </field>
                    <field name="origin_date">
                        <summary>Origin Date</summary>
                    </field>
                </searchable_fields>
            </query>
        </service>

        <struct name="return_update_collection">
            <summary>Return Update Collection</summary>
            <extensible>false</extensible>
            <properties>
                <property name="offset">
                    <summary>Search result offset</summary>
                    <type>integer</type>
                    <required>false</required>
                </property>
                <property name="size">
                    <summary>Max number of entries</summary>
                    <type>integer</type>
                    <required>false</required>
                </property>
                <property name="total">
                    <summary>Total number of records matching search query</summary>
                    <type>integer</type>
                    <required>false</required>
                </property>
                <property name="items">
                    <summary>Matching return updates</summary>
                    <type>array[magento.postsales.return_update]</type>
                    <required>false</required>
                </property>
            </properties>
        </struct>

    </module>

</specification>

=== mdfass/spec-toolkit-java/src/main/resources/shared-services-internal/postsales/appeasement_management.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="https://magento.com/open-specification"
               xsi:schemaLocation="https://magento.com/open-specification ../specification.xsd">

    <module name="magento.postsales">

        <service name="appeasement_management">
            <summary>Appeasement Management</summary>

            <command name="create">
                <summary>Create an appeasement for an order</summary>
                <extensible>true</extensible>
                <status>public</status>
                <arguments>
                    <argument name="appeasement">
                        <summary>Create an appeasement</summary>
                        <type>magento.postsales.appeasement</type>
                        <required>true</required>
                    </argument>
                </arguments>
            </command>

        </service>
    </module>

</specification>

=== mdfass/spec-toolkit-java/src/main/resources/shared-services-internal/source-engine/allocation_queue.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="https://magento.com/open-specification"
               xsi:schemaLocation="https://magento.com/open-specification ../specification.xsd">
    <module name="magento.source_engine">
        <service name="allocation_queue_repository">
            <summary>Allocation Queue Repository</summary>
            <query name="search">
                <summary>Search allocation queue entries using a search query.</summary>
                <description>Searchable fields: order external id</description>
                <extensible>false</extensible>
                <status>draft</status>
                <arguments>
                    <argument name="query">
                        <summary>Query</summary>
                        <type>magento.common.query</type>
                        <required>false</required>
                    </argument>
                </arguments>
                <returns>magento.source_engine.allocation_queue_entry_collection</returns>
                <searchable_fields>
                    <field name="order_id">
                        <summary>Order Id</summary>
                    </field>
                    <field name="status">
                        <summary>Allocation queue entry status</summary>
                    </field>
                </searchable_fields>
            </query>
        </service>

        <service name="allocation_queue_management">
            <summary>Allocation Queue Management</summary>

            <command name="add_order">
                <summary>Add order to allocation queue to be sourced</summary>
                <extensible>false</extensible>
                <status>draft</status>
                <arguments>
                    <argument name="order_id">
                        <summary>Order Id</summary>
                        <type>string</type>
                        <required>true</required>
                    </argument>
                    <argument name="store_id">
                        <summary>Store Id</summary>
                        <type>string</type>
                        <required>true</required>
                    </argument>
                </arguments>
            </command>
        </service>

        <struct name="allocation_queue_entry_collection">
            <summary>Allocation Queue Entry Collection</summary>
            <extensible>false</extensible>
            <properties>
                <property name="offset">
                    <summary>Search result offset</summary>
                    <type>integer</type>
                    <required>false</required>
                </property>
                <property name="size">
                    <summary>Max number of entries</summary>
                    <type>integer</type>
                    <required>false</required>
                </property>
                <property name="total">
                    <summary>Total number of records matching search query</summary>
                    <type>integer</type>
                    <required>false</required>
                </property>
                <property name="items">
                    <summary>Matching allocation queue entries</summary>
                    <type>array[magento.source_engine.allocation_queue_entry]</type>
                    <required>false</required>
                </property>
            </properties>
        </struct>

        <struct name="allocation_queue_entry">
            <summary>Allocation Queue Entry</summary>
            <extensible>false</extensible>
            <properties>
                <property name="order_id">
                    <summary>Order ID</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="status">
                    <summary>Status of the entry in the allocation queue</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="created_by">
                    <summary>Who created the entry</summary>
                    <type>string</type>
                    <required>false</required>
                </property>
                <property name="created_at">
                    <summary>When the entry was created</summary>
                    <type>datetime</type>
                    <required>false</required>
                </property>
                <property name="modified_by">
                    <summary>Who modified the entry last</summary>
                    <type>string</type>
                    <required>false</required>
                </property>
                <property name="modified_at">
                    <summary>When the entry was modified last</summary>
                    <type>datetime</type>
                    <required>false</required>
                </property>
            </properties>
        </struct>
    </module>
</specification>

=== mdfass/spec-toolkit-java/src/main/resources/shared-services-internal/catalog/product.xml
<?xml version="1.0" encoding="UTF-8"?>

<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="https://magento.com/open-specification"
               xsi:schemaLocation="https://magento.com/open-specification ../specification.xsd">

    <module name="magento.catalog">

        <struct name="product">
            <summary>Product</summary>
            <description>
                Product represents the simplest physical or virtual item which can be bought by the customer.
                Product data normally includes a few static fields and a batch of dynamically managed attributes to
                store system information (e.g. is_searchable, ean, country_of_origin etc) and information shown
                to the customer (e.g. long_description, color, or ssd_storage_size etc).
            </description>
            <extensible>true</extensible>
            <properties>
                <property name="id">
                    <summary>Unique Identifier</summary>
                    <type>string</type>
                    <required>true</required>
                </property>

                <property name="type">
                    <summary>Type of product (Simple, Configurable, Virtual...)</summary>
                    <type>magento.catalog.product_type</type>
                    <required>true</required>
                </property>

                <property name="sku">
                    <summary>Stock Keeping Unit of the product</summary>
                    <type>string</type>
                    <required>true</required>
                </property>

                <property name="price_adjustable">
                    <summary>Sets the price as adjustable</summary>
                    <type>boolean</type>
                    <required>false</required>
                </property>

                <property name="name">
                    <summary>Name of the product</summary>
                    <description>
                        Name of the product meant to identify the product in a more human friendly way

                        Example:

                        ```
                        "name": [
                            {"locale": "en_US", "channel": "mobile", "value": "T-Shirt"},
                            {"locale": "es_ES", "channel": "mobile", "value": "Camiseta"}
                        ]
                        ```
                    </description>
                    <type>array[magento.catalog.localized_name]</type>
                    <required>false</required>
                </property>

                <property name="price">
                    <summary>Price of the product</summary>
                    <description>
                        Standard prices of the product.
                    </description>
                    <type>magento.catalog.product_price</type>
                    <required>false</required>
                </property>

                <property name="status">
                    <summary>Status of the product (ACTIVE, INACTIVE, EOL, OUTLET)</summary>
                    <description>
                        The status is only used for the purpose of defining the safety stock at the aggregate level. Each status can have a different safety threshold. Important: the statuses needs to be provided in uppercase.
                    </description>
                    <type>string</type>
                    <required>true</required>
                </property>

                <property name="created_at">
                    <summary>Date of creation of the product</summary>
                    <type>datetime</type>
                    <required>false</required>
                </property>

                <property name="modified_at">
                    <summary>Date of the last modification of the product</summary>
                    <type>datetime</type>
                    <required>false</required>
                </property>

                <property name="children_skus">
                    <summary>If this is a configurable product a list of children (products) skus</summary>
                    <description>
                        An array of products skus corresponding to this product configurations (children)
                    </description>
                    <type>array[string]</type>
                    <required>false</required>
                </property>

                <property name="custom_attributes">
                    <summary>Custom Attributes</summary>
                    <type>array[magento.common.custom_attribute]</type>
                    <required>false</required>
                </property>

            </properties>
        </struct>

        <struct name="product_price">
            <summary>Price of a product including amount and currency</summary>
            <description>Price of a product including amount and currency</description>
            <extensible>false</extensible>
            <properties>
                <property name="currency">
                    <summary>Currency</summary>
                    <type>string</type>
                    <required>true</required>
                </property>

                <property name="amount">
                    <summary>Price amount</summary>
                    <type>float</type>
                    <required>true</required>
                </property>
            </properties>
        </struct>

        <struct name="localized_name">
            <summary>Localized name</summary>
            <description>Name for particular channel and locale</description>
            <extensible>false</extensible>
            <properties>
                <property name="value">
                    <summary>Name</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="channel">
                    <summary>Channel</summary>
                    <type>string</type>
                    <required>false</required>
                </property>
                <property name="locale">
                    <summary>Locale</summary>
                    <type>string</type>
                    <required>false</required>
                </property>
            </properties>
        </struct>

        <enum name="product_type">
            <value>bundle</value>
            <value>configurable</value>
            <value>downloadable</value>
            <value>grouped</value>
            <value>simple</value>
            <value>virtual</value>
            <value>service</value>
            <value>shipping</value>
        </enum>

    </module>
</specification>

=== mdfass/spec-toolkit-java/src/main/resources/shared-services-internal/logistics/reason.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="https://magento.com/open-specification"
               xsi:schemaLocation="https://magento.com/open-specification ../specification.xsd">

    <module name="magento.logistics">

        <service name="reason_repository">
            <summary>Reason Repository</summary>
            <query name="search">
                <summary>Searchs reasons by criteria</summary>
                <extensible>false</extensible>
                <status>public</status>
                <arguments>
                    <argument name="type">
                        <summary>Reason type to search</summary>
                        <type>magento.logistics.reason_type</type>
                        <required>false</required>
                    </argument>
                </arguments>
                <returns>array[magento.logistics.reason]</returns>
            </query>
            <query name="get_reasons">
                <summary>Searchs reasons by criteria</summary>
                <extensible>false</extensible>
                <status>public</status>
                <arguments>
                    <argument name="type">
                        <summary>Reason type to search</summary>
                        <type>magento.logistics.reason_type</type>
                        <required>false</required>
                    </argument>
                </arguments>
                <returns>array[magento.logistics.reason]</returns>
            </query>
        </service>

        <enum name="reason_type">
            <value>pick-decline</value>
            <value>customer-decline</value>
        </enum>

        <struct name="reason">
            <summary>Reason</summary>
            <extensible>false</extensible>
            <properties>
                <property name="type">
                    <summary>Reason type (pick-decline, customer-decline)</summary>
                    <type>magento.logistics.reason_type</type>
                    <required>true</required>
                </property>
                <property name="description">
                    <summary>Description of the reason</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
            </properties>
        </struct>

    </module>
</specification>
