=== mdfass/spec-toolkit-java/src/main/resources/shared-services-internal/specification.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           targetNamespace="https://magento.com/open-specification"
           xmlns="https://magento.com/open-specification"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="specification" type="SpecificationType"/>

  <xs:group name="DescriptionGroup">
    <xs:sequence>
      <xs:element type="xs:string" name="summary" minOccurs="1" maxOccurs="1"/>
      <xs:element type="xs:string" name="description" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:group>

  <xs:complexType name="SpecificationType">
    <xs:sequence>
      <xs:choice maxOccurs="unbounded" minOccurs="0">
        <xs:element type="ImportType" name="import"/>
        <xs:element type="ModuleType" name="module"/>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ModuleType">
    <xs:sequence>
      <xs:choice maxOccurs="unbounded" minOccurs="0">
        <xs:element type="ServiceType" name="service"/>
        <xs:element type="StructType" name="struct"/>
        <xs:element type="EnumType" name="enum"/>
        <xs:element type="ExtensionType" name="extension"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute type="ModuleNameType" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="ImportType">
    <xs:attribute type="xs:token" name="location" use="required"/>
  </xs:complexType>

  <xs:complexType name="ServiceType">
    <xs:sequence>
      <xs:group ref="DescriptionGroup"/>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element type="QueryType" name="query"/>
        <xs:element type="EventType" name="event"/>
        <xs:element type="CommandType" name="command"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute type="ServiceNameType" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="InteractionType" abstract="true">
    <xs:sequence>
      <xs:group ref="DescriptionGroup"/>
      <xs:element type="xs:boolean" name="extensible" minOccurs="1"/>
      <xs:element name="status" type="StatusType" minOccurs="1" maxOccurs="1" />
      <xs:element name="arguments" minOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="PropertyType" name="argument" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="InteractionNameType" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="CommandType">
    <xs:complexContent>
      <xs:extension base="InteractionType">
        <xs:sequence>
          <xs:element type="xs:token" name="returns" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="QueryType">
    <xs:complexContent>
      <xs:extension base="InteractionType">
        <xs:sequence>
          <xs:element type="xs:token" name="returns" minOccurs="1" maxOccurs="1"/>
          <xs:element type="SearchableFieldsType" name="searchable_fields" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="SearchableFieldsType">
    <xs:sequence>
      <xs:element name="field" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:group ref="DescriptionGroup"/>
            <xs:element type="SearchableFieldTypeNameType" name="type" minOccurs="0"/>
          </xs:sequence>
          <xs:attribute name="name" type="SearchableFieldNameType" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="EventType">
    <xs:complexContent>
      <xs:extension base="InteractionType"/>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="StructType" mixed="true">
    <xs:sequence>
      <xs:group ref="DescriptionGroup"/>
      <xs:element type="xs:boolean" name="extensible" minOccurs="1"/>
      <xs:element name="properties" minOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="PropertyType" name="property" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="xs:token" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="ExtensionType" mixed="true">
    <xs:sequence>
      <xs:group ref="DescriptionGroup"/>
      <xs:element name="properties" minOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="PropertyType" name="property" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="xs:token" name="extends" use="required"/>
    <xs:attribute type="xs:token" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="PropertyType">
    <xs:sequence>
      <xs:group ref="DescriptionGroup"/>
      <xs:element type="PropertyTypeNameType" name="type" minOccurs="1"/>
      <xs:element type="xs:boolean" name="required" minOccurs="1"/>
    </xs:sequence>
    <xs:attribute type="xs:token" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="EnumType">
    <xs:sequence>
      <xs:element type="xs:token" name="value" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:token" name="name" use="required"/>
  </xs:complexType>

  <xs:simpleType name="StatusType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="public"/>
      <xs:enumeration value="draft"/>
      <xs:enumeration value="beta"/>
      <xs:enumeration value="deprecated"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="PropertyTypeNameType">
    <xs:restriction base="xs:token" />
  </xs:simpleType>

  <xs:simpleType name="ModuleNameType">
    <xs:restriction base="xs:token">
      <xs:pattern value="[a-z][a-z0-9_]*\.[a-z][a-z0-9_]*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ServiceNameType">
    <xs:restriction base="xs:token">
      <xs:pattern value="[a-z][a-z0-9_]*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="SearchableFieldTypeNameType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="string"/>
      <xs:enumeration value="integer"/>
      <xs:enumeration value="float"/>
      <xs:enumeration value="boolean"/>
      <xs:enumeration value="datetime"/>
      <xs:enumeration value="blob"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="InteractionNameType">
    <xs:restriction base="xs:token">
      <xs:pattern value="[a-z][a-z0-9_]*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="SearchableFieldNameType">
    <xs:restriction base="xs:token">
      <xs:pattern value="[a-zA-Z_]*" />
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== mdfass/spec-toolkit-java/src/main/resources/shared-services-internal/catalog/product_management.xml
<?xml version="1.0" encoding="UTF-8"?>

<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="https://magento.com/open-specification"
               xsi:schemaLocation="https://magento.com/open-specification ../specification.xsd">

    <module name="magento.catalog">

        <service name="product_management">
            <summary>Product Management</summary>

            <event name="updated">
                <summary>Product Updated</summary>
                <description>Triggered once product updated from the source of truth (PIM or Magento Commerce). Will create new products in OMS catalog.
                    The supported type of products are BUNDLE, VIRTUAL, PHYSICAL, SERVICE and SHIPPING.
                </description>
                <extensible>true</extensible>
                <status>public</status>
                <arguments>
                    <argument name="product">
                        <summary>Product</summary>
                        <type>magento.catalog.product</type>
                        <required>true</required>
                    </argument>
                </arguments>
            </event>
        </service>

    </module>
</specification>

=== mdfass/spec-toolkit-java/src/main/resources/shared-services-internal/source-engine/sourcing_request.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="https://magento.com/open-specification"
               xsi:schemaLocation="https://magento.com/open-specification ../specification.xsd">

    <module name="magento.source_engine">
        <service name="sourcing_request_management">
            <summary>Sourcing Request Management</summary>

            <command name="cancel">
                <summary>Cancel an existing Sourcing Request</summary>
                <extensible>false</extensible>
                <status>public</status>
                <arguments>
                    <argument name="sourcing_request_uuid">
                        <summary>Sourcing Request UUID</summary>
                        <type>string</type>
                        <required>true</required>
                    </argument>
                    <argument name="user">
                        <summary>User who cancelled the sourcing request</summary>
                        <type>string</type>
                        <required>false</required>
                    </argument>
                    <argument name="reason">
                        <summary>Reason to cancel the sourcing request</summary>
                        <type>string</type>
                        <required>false</required>
                    </argument>
                </arguments>
            </command>

            <event name="created">
                <summary>New Sourcing Request created event</summary>
                <extensible>false</extensible>
                <status>public</status>
                <arguments>
                    <argument name="sourcing_request">
                        <summary>Sourcing Request</summary>
                        <type>magento.source_engine.sourcing_request</type>
                        <required>true</required>
                    </argument>
                </arguments>
            </event>

            <event name="cancelled">
                <summary>Sourcing Request cancelled event</summary>
                <extensible>false</extensible>
                <status>public</status>
                <arguments>
                    <argument name="sourcing_request_uuid">
                        <summary>Sourcing Request UUID</summary>
                        <type>string</type>
                        <required>true</required>
                    </argument>
                </arguments>
            </event>

        </service>
        
        <struct name="sourcing_request">
            <summary>Entity representing multiple lines of an order to be sourced</summary>
            <extensible>true</extensible>
            <properties>
                <property name="uuid">
                    <summary>UUID of the Sourcing Request</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="mode">
                    <summary>Execution Mode for Sourcing Engine</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="order_uuid">
                    <summary>UUID of the Order</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="order_id">
                    <summary>Id of the Order</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="order_creation_date">
                    <summary>Creation Date of the Order</summary>
                    <type>datetime</type>
                    <required>true</required>
                </property>
                <property name="client">
                    <summary>Client ID</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="store_id">
                    <summary>Store ID</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="aggregate_id">
                    <summary>Aggregate ID</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="shipping_method">
                    <summary>Shipping Method</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="shipping_address">
                    <summary>Address of the Order</summary>
                    <type>magento.common.address</type>
                    <required>true</required>
                </property>
                <property name="lines">
                    <summary>Order Lines to be sourced.</summary>
                    <type>array[magento.source_engine.sourcing_request_line]</type>
                    <required>true</required>
                </property>
                <property name="custom_attributes">
                    <summary>Custom Attributes</summary>
                    <type>array[magento.common.custom_attribute]</type>
                    <required>false</required>
                </property>
            </properties>
        </struct>

        <struct name="sourcing_request_line">
            <summary>Sourcing Request Line</summary>
            <extensible>true</extensible>
            <properties>
                <property name="id">
                    <summary>Order Line ID</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="line_number">
                    <summary>Order Line Number</summary>
                    <type>integer</type>
                    <required>true</required>
                </property>
                <property name="sku">
                    <summary>SKU of the Item</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="product_type">
                    <summary>Product Type</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="parent_line_id">
                    <summary>Order Line External ID of the parent Line</summary>
                    <type>string</type>
                    <required>false</required>
                </property>
                <property name="allocation_attempts">
                    <summary>Number of allocation attempts of this Line</summary>
                    <type>integer</type>
                    <required>false</required>
                </property>
                <property name="source_id">
                    <summary>Source ID for lines already Hard Allocated</summary>
                    <type>string</type>
                    <required>false</required>
                </property>
                <property name="declined_sources">
                    <summary>Declined Sources for a Sourcing Line</summary>
                    <type>array[string]</type>
                    <required>false</required>
                </property>
                <property name="custom_attributes">
                    <summary>Custom Attributes</summary>
                    <type>array[magento.common.custom_attribute]</type>
                    <required>false</required>
                </property>
                <property name="source_location">
                    <summary>Identifier that will force the source to be used when sourcing the order</summary>
                    <description>Note: if no stock is available in this defined source, the order line will remain in backorder. If an order is a ISPU, this field will be used only when Ship To Store is enabled to force the source that will be providing the stock to the final collection point</description>
                    <type>string</type>
                    <required>false</required>
                </property>
                <property name="pickup_location">
                    <summary>Identifier that the customer selected as a collection point</summary>
                    <type>string</type>
                    <required>false</required>
                </property>
                <property name="quantity">
                    <summary>The quantity of the sourcing request</summary>
                    <type>integer</type>
                    <required>true</required>
                </property>
                <property name="promise_delivery_date">
                    <summary>Promise delivery date of the line</summary>
                    <type>datetime</type>
                    <required>false</required>
                </property>
            </properties>
        </struct>
    </module>
</specification>

=== mdfass/spec-toolkit-java/src/main/resources/shared-services-internal/sales/shipping_address_modification.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="https://magento.com/open-specification"
               xsi:schemaLocation="https://magento.com/open-specification ../specification.xsd">

    <module name="magento.sales">

        <struct name="shipping_address">
            <summary>Shipping address information for order modification actions</summary>
            <extensible>false</extensible>
            <properties>
                <property name="reference">
                    <summary>Reference of the new address. It may not be unique or empty</summary>
                    <description>This identifier should be provided by the same system where the order was placed,
                        otherwise although MOM will store it the front end won't be able to process or recognize it.
                        Also mention it could be empty in some cases (for instance if the order modification is
                        initiated by a CS agent using the MOM CS application)
                    </description>
                    <type>string</type>
                    <required>false</required>
                </property>
                <property name="first_name">
                    <summary>First Name of the source</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="last_name">
                    <summary>Last Name of the source</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="company_name">
                    <summary>Company name</summary>
                    <type>string</type>
                    <required>false</required>
                </property>
                <property name="address1">
                    <summary>First line of address description</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="address2">
                    <summary>Second line of address description</summary>
                    <type>string</type>
                    <required>false</required>
                </property>
                <property name="city">
                    <summary>City of the address</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="state">
                    <summary>State of the address</summary>
                    <type>string</type>
                    <required>false</required>
                </property>
                <property name="zip">
                    <summary>Zip code of the address</summary>
                    <type>string</type>
                    <required>false</required>
                </property>
                <property name="country_code">
                    <summary>Country code of the address</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="phone">
                    <summary>Phone of the source</summary>
                    <type>string</type>
                    <required>false</required>
                </property>
                <property name="email">
                    <summary>Email of the source</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="latitude">
                    <summary>Latitude coordinates</summary>
                    <type>string</type>
                    <required>false</required>
                </property>
                <property name="longitude">
                    <summary>Longitude coordinates</summary>
                    <type>string</type>
                    <required>false</required>
                </property>
                <property name="custom_attributes">
                    <summary>Custom Attributes</summary>
                    <type>array[magento.common.custom_attribute]</type>
                    <required>false</required>
                </property>
            </properties>
        </struct>

    </module>

</specification>

=== mdfass/spec-toolkit-java/src/main/resources/shared-services-internal/common/price.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="https://magento.com/open-specification"
               xsi:schemaLocation="https://magento.com/open-specification ../specification.xsd">

    <module name="magento.common">
        <struct name="price">
            <summary>Pricing information of the line</summary>
            <extensible>true</extensible>
            <properties>
                <property name="net_amount">
                    <summary>Net amount of the line</summary>
                    <type>float</type>
                    <required>true</required>
                </property>
                <property name="gross_amount">
                    <summary>Gross amount of the line</summary>
                    <type>float</type>
                    <required>true</required>
                </property>
                <property name="tax_amount">
                    <summary>Total tax amount of the line</summary>
                    <type>float</type>
                    <required>true</required>
                </property>
                <property name="tax_rate">
                    <summary>Total tax rate</summary>
                    <type>float</type>
                    <required>true</required>
                </property>
                <property name="taxes">
                    <summary>Detailed list of taxes applied to the line</summary>
                    <type>array[magento.common.price_tax]</type>
                    <required>true</required>
                </property>
                <property name="currency">
                    <summary>Currency of the amount of the line</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
            </properties>
        </struct>

        <struct name="price_tax">
            <summary>Taxes</summary>
            <extensible>true</extensible>
            <properties>
                <property name="type">
                    <summary>Type of the tax</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="amount">
                    <summary>Amount of tax</summary>
                    <type>float</type>
                    <required>true</required>
                </property>
                <property name="rate">
                    <summary>Tax rate applied</summary>
                    <type>float</type>
                    <required>true</required>
                </property>
            </properties>
        </struct>
    </module>
</specification>

=== mdfass/spec-toolkit-java/src/main/resources/shared-services-internal/common/query.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="https://magento.com/open-specification"
               xsi:schemaLocation="https://magento.com/open-specification ../specification.xsd">

    <module name="magento.common">
        <struct name="query">
            <summary>Search Query</summary>
            <extensible>false</extensible>
            <properties>
                <property name="offset">
                    <summary>Offset</summary>
                    <description>Number of first record to return</description>
                    <type>integer</type>
                    <required>false</required>
                </property>
                <property name="size">
                    <summary>Number of records to return</summary>
                    <type>integer</type>
                    <required>false</required>
                </property>
                <property name="criteria">
                    <summary>Search criteria</summary>
                    <type>magento.common.expression</type>
                    <required>false</required>
                </property>
                <property name="include">
                    <summary>Specify list of extension attributes to be included into records</summary>
                    <type>array[string]</type>
                    <required>false</required>
                </property>
                <property name="order">
                    <summary>Sort order</summary>
                    <type>map[magento.common.order_direction]</type>
                    <required>false</required>
                </property>
            </properties>
        </struct>

        <struct name="expression">
            <summary>Search Criteria</summary>
            <extensible>false</extensible>
            <properties>
                <property name="exp">
                    <summary>Type of the expression</summary>
                    <type>string</type>
                    <required>false</required>
                </property>
                <property name="args">
                    <summary>Arguments</summary>
                    <type>array[magento.common.expression]</type>
                    <required>false</required>
                </property>
                <property name="value">
                    <summary>Constant value expression</summary>
                    <type>string</type>
                    <required>false</required>
                </property>
                <property name="type">
                    <summary>Type of the constant value</summary>
                    <type>string</type>
                    <required>false</required>
                </property>
            </properties>
        </struct>

        <enum name="order_direction">
            <value>ASC</value>
            <value>DESC</value>
        </enum>
    </module>

</specification>

=== mdfass/spec-toolkit-java/src/main/resources/shared-services-internal/logistics/carrier.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="https://magento.com/open-specification"
               xsi:schemaLocation="https://magento.com/open-specification ../specification.xsd">

    <module name="magento.logistics">
        <service name="carrier_management">
            <summary>Carrier Management</summary>

            <query name="request_shipping_details">
                <summary>Request shipping details</summary>
                <description>
                    This message is used to request shipping label and tracking details per order and box
                </description>
                <extensible>false</extensible>
                <status>public</status>
                <arguments>
                    <argument name="shipment">
                        <summary>Shipment</summary>
                        <type>magento.logistics.customer_shipment</type>
                        <required>true</required>
                    </argument>
                </arguments>
                <returns>array[magento.logistics.package]</returns>
            </query>
        </service>
    </module>

</specification>
