=== mdfass/spec-toolkit-java/src/main/resources/shared-services-internal/specification.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           targetNamespace="https://magento.com/open-specification"
           xmlns="https://magento.com/open-specification"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="specification" type="SpecificationType"/>

  <xs:group name="DescriptionGroup">
    <xs:sequence>
      <xs:element type="xs:string" name="summary" minOccurs="1" maxOccurs="1"/>
      <xs:element type="xs:string" name="description" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:group>

  <xs:complexType name="SpecificationType">
    <xs:sequence>
      <xs:choice maxOccurs="unbounded" minOccurs="0">
        <xs:element type="ImportType" name="import"/>
        <xs:element type="ModuleType" name="module"/>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ModuleType">
    <xs:sequence>
      <xs:choice maxOccurs="unbounded" minOccurs="0">
        <xs:element type="ServiceType" name="service"/>
        <xs:element type="StructType" name="struct"/>
        <xs:element type="EnumType" name="enum"/>
        <xs:element type="ExtensionType" name="extension"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute type="ModuleNameType" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="ImportType">
    <xs:attribute type="xs:token" name="location" use="required"/>
  </xs:complexType>

  <xs:complexType name="ServiceType">
    <xs:sequence>
      <xs:group ref="DescriptionGroup"/>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element type="QueryType" name="query"/>
        <xs:element type="EventType" name="event"/>
        <xs:element type="CommandType" name="command"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute type="ServiceNameType" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="InteractionType" abstract="true">
    <xs:sequence>
      <xs:group ref="DescriptionGroup"/>
      <xs:element type="xs:boolean" name="extensible" minOccurs="1"/>
      <xs:element name="status" type="StatusType" minOccurs="1" maxOccurs="1" />
      <xs:element name="arguments" minOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="PropertyType" name="argument" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="InteractionNameType" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="CommandType">
    <xs:complexContent>
      <xs:extension base="InteractionType">
        <xs:sequence>
          <xs:element type="xs:token" name="returns" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="QueryType">
    <xs:complexContent>
      <xs:extension base="InteractionType">
        <xs:sequence>
          <xs:element type="xs:token" name="returns" minOccurs="1" maxOccurs="1"/>
          <xs:element type="SearchableFieldsType" name="searchable_fields" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="SearchableFieldsType">
    <xs:sequence>
      <xs:element name="field" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:group ref="DescriptionGroup"/>
            <xs:element type="SearchableFieldTypeNameType" name="type" minOccurs="0"/>
          </xs:sequence>
          <xs:attribute name="name" type="SearchableFieldNameType" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="EventType">
    <xs:complexContent>
      <xs:extension base="InteractionType"/>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="StructType" mixed="true">
    <xs:sequence>
      <xs:group ref="DescriptionGroup"/>
      <xs:element type="xs:boolean" name="extensible" minOccurs="1"/>
      <xs:element name="properties" minOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="PropertyType" name="property" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="xs:token" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="ExtensionType" mixed="true">
    <xs:sequence>
      <xs:group ref="DescriptionGroup"/>
      <xs:element name="properties" minOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="PropertyType" name="property" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="xs:token" name="extends" use="required"/>
    <xs:attribute type="xs:token" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="PropertyType">
    <xs:sequence>
      <xs:group ref="DescriptionGroup"/>
      <xs:element type="PropertyTypeNameType" name="type" minOccurs="1"/>
      <xs:element type="xs:boolean" name="required" minOccurs="1"/>
    </xs:sequence>
    <xs:attribute type="xs:token" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="EnumType">
    <xs:sequence>
      <xs:element type="xs:token" name="value" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:token" name="name" use="required"/>
  </xs:complexType>

  <xs:simpleType name="StatusType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="public"/>
      <xs:enumeration value="draft"/>
      <xs:enumeration value="beta"/>
      <xs:enumeration value="deprecated"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="PropertyTypeNameType">
    <xs:restriction base="xs:token" />
  </xs:simpleType>

  <xs:simpleType name="ModuleNameType">
    <xs:restriction base="xs:token">
      <xs:pattern value="[a-z][a-z0-9_]*\.[a-z][a-z0-9_]*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ServiceNameType">
    <xs:restriction base="xs:token">
      <xs:pattern value="[a-z][a-z0-9_]*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="SearchableFieldTypeNameType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="string"/>
      <xs:enumeration value="integer"/>
      <xs:enumeration value="float"/>
      <xs:enumeration value="boolean"/>
      <xs:enumeration value="datetime"/>
      <xs:enumeration value="blob"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="InteractionNameType">
    <xs:restriction base="xs:token">
      <xs:pattern value="[a-z][a-z0-9_]*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="SearchableFieldNameType">
    <xs:restriction base="xs:token">
      <xs:pattern value="[a-zA-Z_]*" />
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== mdfass/spec-toolkit-java/src/main/resources/shared-services-internal/sales/preorder.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="https://magento.com/open-specification"
               xsi:schemaLocation="https://magento.com/open-specification ../specification.xsd">

    <module name="magento.sales">

        <service name="preorder_management">
            <summary>Pre-order Management</summary>

            <command name="change_street_date">
                <summary>Change the street date for the specified pre-ordered items.</summary>
                <description>Change the street date for the pre-ordered items specified in the command. Will not change
                    order items with street dates in the past, or that have already been allocated or otherwise
                    finalized.</description>
                <extensible>false</extensible>
                <status>beta</status>

                <arguments>
                    <argument name="skus">
                        <summary>The SKUs of the pre-ordered items to be updated.</summary>
                        <type>array[string]</type>
                        <required>true</required>
                    </argument>

                    <argument name="current_street_date">
                        <summary>Only update the pre-ordered items that have this street date.</summary>
                        <description>Only update the pre-ordered items that have this current street date. This
                            includes all street dates within the same hour as specified.</description>
                        <type>datetime</type>
                        <required>false</required>
                    </argument>

                    <argument name="new_street_date">
                        <summary>The new street date for the pre-ordered items.</summary>
                        <type>datetime</type>
                        <required>true</required>
                    </argument>

                    <argument name="ship_to_countries">
                        <summary>Only update the pre-ordered items with a ship to country in this list.</summary>
                        <type>array[string]</type>
                        <required>false</required>
                    </argument>

                    <argument name="sales_channel_ids">
                        <summary>Only update the pre-ordered items for the specified sales channels.</summary>
                        <type>array[string]</type>
                        <required>false</required>
                    </argument>
                </arguments>
            </command>

            <event name="street_date_changed">
                <summary>Notification that the street date for pre-ordered items has changed.</summary>
                <extensible>false</extensible>
                <status>beta</status>
                <arguments>
                    <argument name="skus">
                        <summary>The SKUs of the pre-ordered items that were updated.</summary>
                        <type>array[string]</type>
                        <required>true</required>
                    </argument>

                    <argument name="previous_street_date">
                        <summary>The previous street date for the pre-ordered items.</summary>
                        <type>datetime</type>
                        <required>false</required>
                    </argument>

                    <argument name="new_street_date">
                        <summary>The new street date for the pre-ordered items.</summary>
                        <type>datetime</type>
                        <required>true</required>
                    </argument>

                    <argument name="ship_to_countries">
                        <summary>The ship to countries for which the street date was updated.</summary>
                        <type>array[string]</type>
                        <required>false</required>
                    </argument>

                    <argument name="sales_channel_ids">
                        <summary>The sales channels in which the street date was updated.</summary>
                        <type>array[string]</type>
                        <required>false</required>
                    </argument>

                </arguments>
            </event>
        </service>
    </module>
</specification>

=== mdfass/spec-toolkit-java/src/main/resources/shared-services-internal/common/log_entry.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="https://magento.com/open-specification"
               xsi:schemaLocation="https://magento.com/open-specification ../specification.xsd">

    <module name="magento.common">
        <struct name="log_entry">
            <summary>Log entry</summary>
            <extensible>true</extensible>
            <properties>
                <property name="type">
                    <summary>Log type</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="category">
                    <summary>Log category</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="level">
                    <summary>Log level</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="message">
                    <summary>Log message</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="context">
                    <summary>Log context</summary>
                    <type>map[string]</type>
                    <required>false</required>
                </property>
            </properties>
        </struct>

        <service name="log_entry_management">
            <summary>Log entry Management</summary>
            <command name="publish">
                <summary>Publish a log entry</summary>
                <extensible>false</extensible>
                <status>public</status>
                <arguments>
                    <argument name="log_entry">
                        <summary>Log entry</summary>
                        <type>magento.common.log_entry</type>
                        <required>true</required>
                    </argument>
                </arguments>
            </command>
        </service>
    </module>

</specification>

=== mdfass/spec-toolkit-java/src/main/resources/shared-services-internal/common/general.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="https://magento.com/open-specification"
               xsi:schemaLocation="https://magento.com/open-specification ../specification.xsd">

    <module name="magento.common">
        <struct name="custom_attribute">
            <summary>Custom Attribute</summary>
            <extensible>false</extensible>
            <properties>
                <property name="name">
                    <summary>Name of the attribute</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="value">
                    <summary>Value of the attribute</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
            </properties>
        </struct>
    </module>

</specification>

=== mdfass/spec-toolkit-java/src/main/resources/shared-services-internal/logistics/shipment_repository.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="https://magento.com/open-specification"
               xsi:schemaLocation="https://magento.com/open-specification ../specification.xsd">

    <module name="magento.logistics">

        <service name="shipment_repository">
            <summary>Shipment Repository</summary>

            <query name="search">
                <summary>Searchs shipments by criteria</summary>
                <extensible>false</extensible>
                <status>draft</status>
                <arguments>
                    <argument name="query">
                        <summary>Query</summary>
                        <type>magento.common.query</type>
                        <required>false</required>
                    </argument>
                </arguments>
                <returns>magento.logistics.shipment_collection</returns>
                <searchable_fields>
                    <field name="sales_channel_id">
                        <summary>Sales channel ID</summary>
                        <description>Uniquely identifies a sales channel</description>
                        <type>string</type>
                    </field>
                    <field name="order_id">
                        <summary>Order external ID</summary>
                        <description>Uniquely identifies a single order. Usually provided by the front end</description>
                        <type>string</type>
                    </field>
                    <field name="source_id">
                        <summary>Source external ID</summary>
                        <description>Uniquely identifies a single source</description>
                        <type>string</type>
                    </field>
                    <field name="shipment_request_id">
                        <summary>Shipment request external ID</summary>
                        <description>Uniquely identifies a shipment request</description>
                        <type>string</type>
                    </field>
                    <field name="carrier">
                        <summary>Carrier</summary>
                        <type>string</type>
                    </field>
                    <field name="method">
                        <summary>Shipment Method</summary>
                        <description>Shipment method used (e.g. STANDARD, EXPRESS, ISPU, etc)</description>
                        <type>string</type>
                    </field>
                    <field name="status">
                        <summary>Shipment status</summary>
                        <description>Current status of the shipment</description>
                        <type>string</type>
                    </field>
                    <field name="shipment_status_date">
                        <summary>Shipment status date</summary>
                        <description>Date when the status was updated</description>
                        <type>string</type>
                    </field>
                    <field name="shipment_request_date">
                        <summary>Shipment request date</summary>
                        <description>Date when the shipment_request was generated</description>
                        <type>string</type>
                    </field>
                </searchable_fields>
            </query>
        </service>

        <struct name="shipment_collection">
            <summary>Shipment Collection</summary>
            <extensible>false</extensible>
            <properties>
                <property name="offset">
                    <summary>Search result offset</summary>
                    <type>integer</type>
                    <required>false</required>
                </property>
                <property name="size">
                    <summary>Max number of entries</summary>
                    <type>integer</type>
                    <required>false</required>
                </property>
                <property name="total">
                    <summary>Total number of records matching search query</summary>
                    <type>integer</type>
                    <required>false</required>
                </property>
                <property name="items">
                    <summary>Matching shipments</summary>
                    <type>array[magento.logistics.shipment]</type>
                    <required>false</required>
                </property>
            </properties>
        </struct>

    </module>
</specification>

=== mdfass/spec-toolkit-java/src/main/resources/shared-services-internal/sales/order_repository.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="https://magento.com/open-specification"
               xsi:schemaLocation="https://magento.com/open-specification ../specification.xsd">
    <module name="magento.sales">
        <service name="order_repository">
            <summary>Order Repository</summary>
            <query name="search">
                <summary>Search orders using a search query.</summary>
                <extensible>false</extensible>
                <status>public</status>
                <arguments>
                    <argument name="query">
                        <summary>Query</summary>
                        <type>magento.common.query</type>
                        <required>false</required>
                    </argument>
                </arguments>
                <returns>magento.sales.order_collection</returns>
                <searchable_fields>
                    <field name="id">
                        <summary>Order external ID</summary>
                        <description>Uniquely identifies a single order. Usually provided by the front end</description>
                        <type>string</type>
                    </field>
                    <field name="customer_id">
                        <summary>Customer identification</summary>
                    </field>
                    <field name="customer_first_name">
                        <summary>Customer first name</summary>
                    </field>
                    <field name="customer_last_name">
                        <summary>Customer last name</summary>
                    </field>
                    <field name="customer_email">
                        <summary>Customer email address</summary>
                    </field>
                    <field name="customer_phone">
                        <summary>Customer phonenumber</summary>
                    </field>
                    <field name="address_first_line">
                        <summary>Address first line</summary>
                    </field>
                    <field name="address_country">
                        <summary>Address first line</summary>
                    </field>
                    <field name="address_zip">
                        <summary>Address ZIP code</summary>
                    </field>
                    <field name="address_state">
                        <summary>Address state</summary>
                    </field>
                    <field name="history_status">
                        <summary>Historical status. It will return all orders that have ever been in status specified. This field provides more use when used in conjunction with history_date (for example: Get all orders that were in status "LOGISTICS" between January 20th and January 21st)</summary>
                    </field>
                    <field name="history_date">
                        <summary>Historical date. It should be used in conjunction with the history_status to filter orders that had a specific status during the defined timeframe.</summary>
                    </field>
                    <field name="status">
                        <summary>Order status</summary>
                    </field>
                    <field name="status_reason">
                        <summary>Status reason</summary>
                    </field>
                    <field name="origin_date">
                        <summary>Origin date</summary>
                    </field>
                    <field name="origin">
                        <summary>Order origin</summary>
                    </field>
                    <field name="payment_method">
                        <summary>Payment method</summary>
                    </field>
                    <field name="sales_channel">
                        <summary>Sales channel</summary>
                    </field>
                    <field name="sku">
                        <summary>SKU</summary>
                    </field>
                    <field name="product_type">
                        <summary>Product type</summary>
                    </field>
                    <field name="source_id">
                        <summary>Source Id [*deprecated*]</summary>
                    </field>
                    <field name="shipping_method">
                        <summary>Shipping method</summary>
                    </field>
                    <field name="source_location">
                        <summary>Source that was used to hard allocate the order line</summary>
                    </field>
                    <field name="pickup_location">
                        <summary>Identifier that the customer selected as a collection point (only used for ISPU orders)</summary>
                    </field>
                    <field name="attribute_key">
                        <summary>Custom attributes</summary>
                    </field>
                    <field name="attribute_value">
                        <summary>Custom attributes</summary>
                    </field>
                    <field name="order_item_attribute_key">
                        <summary>Order item custom attributes</summary>
                    </field>
                    <field name="order_item_attribute_value">
                        <summary>Order item custom attributes</summary>
                    </field>
                    <field name="order_item_status">
                        <summary>Order item status</summary>
                    </field>
                    <field name="order_item_status_reason">
                        <summary>Order item status reason</summary>
                    </field>
                    <field name="total_source_allocations">
                        <summary>Number of total successful source allocations for each line</summary>
                    </field>
                </searchable_fields>
            </query>

            <query name="find">
                <summary>Find and retrieve an order by its id at a given sales channel.</summary>
                <extensible>false</extensible>
                <status>draft</status>
                <arguments>
                    <argument name="id">
                        <summary>Order id</summary>
                        <type>string</type>
                        <required>true</required>
                    </argument>
                    <argument name="sales_channel_id">
                        <summary>Sales channel id</summary>
                        <type>string</type>
                        <required>true</required>
                    </argument>
                </arguments>
                <returns>magento.sales.order</returns>
            </query>
        </service>
    </module>
</specification>

=== mdfass/spec-toolkit-java/src/main/resources/shared-services-internal/postsales/shipping_address.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="https://magento.com/open-specification"
               xsi:schemaLocation="https://magento.com/open-specification ../specification.xsd">

    <module name="magento.postsales">
        <struct name="shipping_address">
            <summary>Shipping address information</summary>
            <extensible>true</extensible>
            <properties>
                <property name="first_name">
                    <summary>First Name</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="last_name">
                    <summary>Last Name</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="company_name">
                    <summary>Company name</summary>
                    <type>string</type>
                    <required>false</required>
                </property>
                <property name="address1">
                    <summary>First line of address description</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="address2">
                    <summary>Second line of address description</summary>
                    <type>string</type>
                    <required>false</required>
                </property>
                <property name="city">
                    <summary>City of the address</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="zip">
                    <summary>Zip code of the address</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
                <property name="state">
                    <summary>State of the address</summary>
                    <type>string</type>
                    <required>true</required>
                </property>
            </properties>
        </struct>
    </module>
</specification>
